version: '3.8'

services:
  backend:
    extends:
      file: ./server/docker-compose.yml
      service: production
    environment:
      FRONTEND_URL: "http://localhost:5173"
  database:
    extends:
      file: ./server/docker-compose.yml
      service: database
  database-client:
    extends:
      file: ./server/docker-compose.yml
      service: database-client
  frontend:
    extends:
      file: ./client/docker-compose.yml
      service: production
    depends_on: [backend]

volumes:
  database-data:
    name: database-data
    external: true
  database-client-data:
    name: database-client-data
    external: true

networks:
  backend-network:
    name: backend-network