version: '3.8'

services:
  backend:
    extends:
      file: ./server/docker-compose.yml
      service: production
    environment:
      SERVER_HOST: $SERVER_HOST
    networks: [app-network, server-network]
  database:
    extends:
      file: ./server/docker-compose.yml
      service: database
  database-client:
    extends:
      file: ./server/docker-compose.yml
      service: database-client
  frontend:
    extends:
      file: ./client/docker-compose.yml
      service: production
    depends_on: 
      backend:
        condition: service_healthy
    volumes:
      - $PWD/client/src:/usr/src/app/src
    hostname: $FRONTEND_HOST
    networks: [app-network]
    environment:
      SERVER_HOST: $SERVER_HOST
  web-server:
    build:
      context: ./web-server
    depends_on: [frontend]
    ports: ["2000:2000"]
    restart: unless-stopped
    expose: ["2000"]
    networks: [app-network]
    environment:
      BACKEND_HOST:  $BACKEND_HOST
      BACKEND_PORT:  $BACKEND_PORT
      FRONTEND_HOST: $FRONTEND_HOST
      FRONTEND_PORT: $FRONTEND_PORT

volumes:
  database-data:
    name: database-data
  database-client-data:
    name: database-client-data

networks:
  app-network:
    name: app-network
  server-network:
    name: server-network