version: "3.8"

services:
  # Database -------------------------------------------------------------------------------------------------
  database:
    image: postgres:15
    container_name: $DATABASE_HOST
    restart: always
    expose: [$DATABASE_PORT]
    ports: [$DATABASE_PORT:$DATABASE_PORT] # for development only
    volumes: [database-data:/var/lib/postgresql/data]
    networks: [app-network]
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      PGPORT: $DATABASE_PORT
  # pgAdmin -------------------------------------------------------------------------------------------------
  pgAdmin:
    image: dpage/pgadmin4:7
    container_name: $PGADMIN_HOST
    restart: always
    expose: [$PGADMIN_PORT]
    ports: [$PGADMIN_PORT:$PGADMIN_PORT]
    networks: [app-network]
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: $PGADMIN_PORT
  # Backend -------------------------------------------------------------------------------------------------
  backend:
    depends_on: [database]
    build: ./backend
    image: backend
    container_name: $BACKEND_HOST
    restart: always
    networks: [app-network]
    expose: [$BACKEND_PORT]
    ports: [$BACKEND_PORT:$BACKEND_PORT] # for development only
  # Frontend ------------------------------------------------------------------------------------------------
  frontend:
    depends_on: [backend]
    build: ./frontend
    image: frontend
    container_name: $FRONTEND_HOST
    restart: always
    networks: [app-network]
    expose: [$FRONTEND_PORT]
    ports: [$FRONTEND_PORT:$FRONTEND_PORT]

volumes:
  database-data:
    name: database-data

networks:
  app-network:
    name: app-network