version: "3.8"

services:
  # Database -------------------------------------------------------------------------------------------------
  database:
    image: postgres:15-alpine
    container_name: $DATABASE_HOST
    restart: always
    expose: [$DATABASE_PORT]
    ports: [$DATABASE_PORT:$DATABASE_PORT] # for development only
    volumes: [database-data:/var/lib/postgresql/data]
    networks: [app-network]
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
      PGPORT: $DATABASE_PORT
    healthcheck:
      test: pg_isready -U $DATABASE_USER -d $DATABASE_NAME
      interval: 1s
      retries: 5
      start_period: 2s
  # pgAdmin -------------------------------------------------------------------------------------------------
  database-client:
    depends_on:
      database:
        condition: service_healthy
    image: dbeaver/cloudbeaver:23.0.4
    container_name: database-client
    restart: always
    expose: [8978]
    ports: [8978:8978]
    networks: [app-network]
    volumes: [database-client-data:/opt/cloudbeaver/data]
  # Backend -------------------------------------------------------------------------------------------------
  backend:
    depends_on:
      database:
        condition: service_healthy
    build: ./backend
    image: backend
    container_name: backend
    restart: always
    networks: [app-network]
    expose: [$BACKEND_PORT]
    ports: [$BACKEND_PORT:$BACKEND_PORT]
    env_file: [.env]
    environment:
      DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME?schema=public"
  # Frontend ------------------------------------------------------------------------------------------------
  frontend:
    depends_on: [backend]
    build: ./frontend
    image: frontend
    container_name: frontend
    restart: always
    networks: [app-network]
    expose: [80]
    ports: [80:80]

volumes:
  database-data:
    name: database-data
  database-client-data:
    name: database-client-data

networks:
  app-network:
    name: app-network